In [1]:
import json
import pandas as pd

In [2]:
with open('data/CountryVD-PingtungCounty.json', 'r', encoding='utf-8') as f:
        CountryVD = json.load(f)

In [3]:
pd_CountryVD = pd.DataFrame(CountryVD)
pd_CountryVD = pd.DataFrame(pd_CountryVD, columns=['VDs'])
pd_CountryVD

                                                  VDs
0   {'VDID': 'V500101', 'BiDirectional': 1, 'Detec...
1   {'VDID': 'V500201', 'BiDirectional': 1, 'Detec...
2   {'VDID': 'V500401', 'BiDirectional': 1, 'Detec...
3   {'VDID': 'V500701', 'BiDirectional': 1, 'Detec...
4   {'VDID': 'V501301', 'BiDirectional': 1, 'Detec...
5   {'VDID': 'V501401', 'BiDirectional': 1, 'Detec...
6   {'VDID': 'V501501', 'BiDirectional': 1, 'Detec...
7   {'VDID': 'V501901', 'BiDirectional': 1, 'Detec...
8   {'VDID': 'V502101', 'BiDirectional': 1, 'Detec...
9   {'VDID': 'V502201', 'BiDirectional': 0, 'Detec...
10  {'VDID': 'V502901', 'BiDirectional': 1, 'Detec...
11  {'VDID': 'V503101', 'BiDirectional': 1, 'Detec...
12  {'VDID': 'V504101', 'BiDirectional': 1, 'Detec...
13  {'VDID': 'V504201', 'BiDirectional': 1, 'Detec...

In [4]:
pd_CountryVD['VDID'] = pd_CountryVD['VDs'].apply(lambda x : x['VDID'])
pd_CountryVD['DetectionLinks'] = pd_CountryVD['VDs'].apply(lambda x : x['DetectionLinks'])
pd_CountryVD['PositionLat'] = pd_CountryVD['VDs'].apply(lambda x : x['PositionLat'])
pd_CountryVD['PositionLon'] = pd_CountryVD['VDs'].apply(lambda x : x['PositionLon'])
pd_CountryVD = pd_CountryVD.drop(columns='VDs')
pd_CountryVD = pd_CountryVD.explode('DetectionLinks')
pd_CountryVD['LinkID'] = pd_CountryVD['DetectionLinks'] .apply(lambda x: x['LinkID'])
pd_CountryVD = pd_CountryVD.drop(columns='DetectionLinks')

In [5]:
pd_CountryVD

       VDID  PositionLat  PositionLon          LinkID
0   V500101    22.478621   120.544474  3000100042469T
0   V500101    22.478621   120.544474  3000100142469T
1   V500201    22.406155   120.569621  3001700026976T
1   V500201    22.406155   120.569621  3001700126975T
2   V500401    22.136813   120.704153  3002600000912T
2   V500401    22.136813   120.704153  3002600100912T
3   V500701    22.438880   120.511255  3001700026269T
3   V500701    22.438880   120.511255  3001700126269T
4   V501301    22.495040   120.447650  3001700025201T
4   V501301    22.495040   120.447650  3001700125201T
5   V501401    22.377930   120.598371  3000100043714T
5   V501401    22.377930   120.598371  3000100143713T
6   V501501    22.458012   120.550587  3000100042710T
6   V501501    22.458012   120.550587  3000100142710T
7   V501901    22.207894   120.697974  3000900045141T
7   V501901    22.207894   120.697974  3000900145141T
8   V502101    22.649737   120.447176  3000100039238T
8   V502101    22.649737   120.447176  3000100139238T
9   V502201    22.649711   120.446909  3000100039238T
10  V502901    22.446445   120.558978  3000100042858T
10  V502901    22.446445   120.558978  3000100142859T
11  V503101    22.210971   120.685260  3000100045751T
11  V503101    22.210971   120.685260  3000100145750T
12  V504101    22.394382   120.618840  6742820000040T
12  V504101    22.394382   120.618840  6742820400040T
13  V504201    22.257565   120.653505  3000100045223T
13  V504201    22.257565   120.653505  3000100145223T

In [6]:
with open(f'data/CountrySection-PingtungCounty.json', 'r', encoding='utf-8') as f:
        CountrySection = json.load(f)
        
pd_CountrySection = pd.DataFrame(CountrySection)
pd_CountrySection = pd.DataFrame(pd_CountrySection['Sections'])    
pd_CountrySection['SectionID'] = pd_CountrySection['Sections'].apply(lambda x : x['SectionID'])
pd_CountrySection['LinkIDs'] = pd_CountrySection['Sections'].apply(lambda x: x['LinkIDs'] if 'LinkIDs' in x else "")
pd_CountrySection = pd_CountrySection.drop(columns='Sections')
pd_CountrySection = pd_CountrySection.explode('LinkIDs')
pd_CountrySection['LinkID'] = pd_CountrySection['LinkIDs'].apply(lambda x: x['LinkID'] if isinstance(x, dict) else "")
pd_CountrySection = pd_CountrySection.drop(columns = 'LinkIDs')

pd_CountrySection

   SectionID          LinkID
0        1-3  3000100043645T
0        1-3  3000100043714T
0        1-3  3000100043867T
1        3-5  3000100043895T
1        3-5  3000100043916T
..       ...             ...
74     71-27  3000100042442T
74     71-27  3000100042513T
75     28-72  3000100142578T
75     28-72  3000100142388T
75     28-72  3000100142327T

[454 rows x 2 columns]

In [ ]:
{'SectionID': {0: 'C031420103', 1: 'C031480118', 2: 'C031480108', 3: 'C031480114', 4: 'C031480202', 5: 'C031480203', 6: 'C031440105', 7: 'C031480115', 8: 'C031480212', 9: 'C031480213', 10: 'C031440114', 11: 'C031480103', 12: 'C031500111', 13: 'C031390111', 14: 'C031420104', 15: 'C031420105', 16: 'C031440101', 17: 'C031480104', 18: 'C031480106', 19: 'C050030001', 20: 'C031390112', 21: 'C031370101', 22: 'C050040001', 23: 'C050040011', 24: 'C031370104', 25: 'C031410101', 26: 'C031410106', 27: 'C031440104', 28: 'C031410111', 29: 'C031410116', 30: 'C050020014', 31: 'C031340102', 32: 'C031340103', 33: 'C031370111', 34: 'C031370114', 35: 'C031390101', 36: 'C031390102', 37: 'C031390104', 38: 'C031420113', 39: 'C031420114', 40: 'C031420115', 41: 'C031440115', 42: 'C031420116', 43: 'C031340113', 44: 'C031340114', 45: 'C031350203', 46: 'C031350213', 47: 'C031390202', 48: 'C031390212', 49: 'C031410102', 50: 'C050030002', 51: 'C031390214', 52: 'C050020011', 53: 'C050010011', 54: 'C031340104', 55: 'C031342103', 56: 'C031370102', 57: 'C050030012', 58: 'C031410103', 59: 'C031390204', 60: 'C031350101', 61: 'C050020012', 62: 'C031390114', 63: 'C031340116', 64: 'C031390201', 65: 'C031420106', 66: 'C031340111', 67: 'C031342101', 68: 'C050030011', 69: 'C050020004', 70: 'C031340112', 71: 'C050010001', 72: 'C031500102', 73: 'C031480101', 74: 'C031500103', 75: 'C031410112', 76: 'C031370103', 77: 'C031410114', 78: 'C031390211', 79: 'C031410115', 80: 'C031420101', 81: 'C031480105', 82: 'C031420112', 83: 'C031480109', 84: 'C031420111', 85: 'C031480113', 86: 'C031350211', 87: 'C031480107', 88: 'C031350212', 89: 'C031350201', 90: 'C031440111', 91: 'C031480116', 92: 'C031480117', 93: 'C031440106', 94: 'C031440116', 95: 'C031440113', 96: 'C031440103', 97: 'C031440102', 98: 'C031390213', 99: 'C031370113', 100: 'C031410104', 101: 'C031410113', 102: 'C050020002', 103: 'C031342111', 104: 'C050020001', 105: 'C031350111', 106: 'C031390215', 107: 'C050020013', 108: 'C031500101', 109: 'C031500113', 110: 'C031340106', 111: 'C031410105', 112: 'C031480102', 113: 'C031480119', 114: 'C031342102', 115: 'C031390205', 116: 'C031440112', 117: 'C031480111', 118: 'C031340101', 119: 'C031340105', 120: 'C031340115', 121: 'C031342112', 122: 'C031342113', 123: 'C031350202', 124: 'C031350204', 125: 'C031350214', 126: 'C031370112', 127: 'C031390103', 128: 'C031390113', 129: 'C031390203', 130: 'C031420102', 131: 'C031480112', 132: 'C031480201', 133: 'C031480211', 134: 'C031500112', 135: 'C050020003'}, 'LinkID': {0: '4014200000958N', 1: '4014800101547N', 2: '4014800001626N', 3: '4014800101879N', 4: '6577300200040N', 5: '4014800002840N', 6: '4014400000860N', 7: '4014800101781N', 8: '6568380600010N', 9: '4014800102817N', 10: '4014400100550N', 11: '4014800002228N', 12: '6566740600100N', 13: '4013900100440N', 14: '4014200000403N', 15: '6584070200000N', 16: '4014400000000N', 17: '4014800002020N', 18: '4014800001771N', 19: '6563570300010N', 20: '4013900100131N', 21: '6562550400000N', 22: '6582200200020N', 23: '6582200600000N', 24: '6562660300000N', 25: '6563370400010N', 26: '6577690400020N', 27: '4014400000860N', 28: '6563370000020N', 29: '6577620000020N', 30: '6577370300000N', 31: '6583840300020N', 32: '6583830300010N', 33: '6562640000000N', 34: '6562550000060N', 35: '4013900000440N', 36: '4013900000435N', 37: '4013900000012N', 38: '4014200100693N', 39: '4014200100272N', 40: '6584080700010N', 41: '4014400100860N', 42: '6563260700070N', 43: '6583830700000N', 44: '6583830700020N', 45: '6580030100020N', 46: '6580010500010N', 47: '6584110300020N', 48: '6584110700010N', 49: '6563370400030N', 50: '6563570300050N', 51: '6584100000050N', 52: '6577340700000N', 53: '6577880000000N', 54: '6583830300040N', 55: '6585870500020N', 56: '6562550400030N', 57: '6563570700020N', 58: '6563850400030N', 59: '6584100400050N', 60: '6580620300100N', 61: '6577330000010N', 62: '4013900100000N', 63: '6568390000030N', 64: '6584110300000N', 65: '6584080300000N', 66: '6583850700050N', 67: '6585890500000N', 68: '6563570700000N', 69: '6577350100000N', 70: '6583840700010N', 71: '6577880400020N', 72: '6566740200090N', 73: '6577420200000N', 74: '6566740200050N', 75: '6563370000030N', 76: '6562550400060N', 77: '6563850000040N', 78: '6584120700040N', 79: '6577620000000N', 80: '4014200001119N', 81: '4014800001813N', 82: '4014200100972N', 83: '4014800001521N', 84: '4014200101094N', 85: '4014800102087N', 86: '6568870500050N', 87: '4014800001713N', 88: '6568870500010N', 89: '6568870100020N', 90: '4014400100000N', 91: '4014800101713N', 92: '4014800101626N', 93: '1007600001100N', 94: '1007600101090N', 95: '4014400100319N', 96: '4014400000469N', 97: '4014400000241N', 98: '6584100000000N', 99: '6562550000040N', 100: '6563850400050N', 101: '6563370000050N', 102: '6577320500020N', 103: '6585900000010N', 104: '6577330400000N', 105: '6580620700070N', 106: '6584090000000N', 107: '6577310200000N', 108: '6566780300070N', 109: '6566740600020N', 110: '6568390400040N', 111: '6577620400010N', 112: '4014800002329N', 113: '4014800101507N', 114: '6585880400000N', 115: '6584090400010N', 116: '4014400100119N', 117: '6577430500000N', 118: '6583840300000N', 119: '6568390400000N', 120: '6583830700050N', 121: '6585880000000N', 122: '6585870100000N', 123: '6580010100020N', 124: '6580030100010N', 125: '6580030500020N', 126: '6562550000010N', 127: '4013900000040N', 128: '4013900100021N', 129: '6584100400050N', 130: '4014200000972N', 131: '4014800102229N', 132: '6568380200000N', 133: '6577420600010N', 134: '6566740600060N', 135: '6577370700010N'}}
{'VDID': {}, 'PositionLat': {}, 'PositionLon': {}, 'LinkID': {}}